---
title: Scope
description: Dash
---

### Brief description

Number of stars in the main repository: 16,048\
\
There are 22,334,316 questions open on Stack Overflow, but if we do a keyword search with "Dash", there are 500 questions open.\
\
There are a few forums apart from Stack Overflow, where one can post their questions related to Dash. A few of them are:\
1. [Plotly](https://community.plotly.com/t/how-to-get-your-questions-answered-on-the-plotly-forum/40551)\
2. [Quora](https://www.quora.com)\
3. [qandeelacademy](https://www.qandeelacademy.com)

Number of issues opened in the main repository: 557

### Long description

[How popular is the Dash app?]{.ul}

The current industry leaders in the python dashboarding ecosystem are **Streamlit, Plotly Dash, Voilà, and Panel**.

-   **Deployment**

Dash apps can be deployed on any servers which support Flask app deployment. Nearly all of the major cloud providers support deployment of Flask applications, and consequently Dash applications. It is possible to deploy a Dash application to AWS, Azure, Google Cloud Platform, and many other cloud providers. Dash apps can also be deployed on an Apache webserver using the '[mod_swgi](https://flask.palletsprojects.com/en/1.1.x/deploying/mod_wsgi/)' Apache HTTP Server module, and also on an Nginx webserver.

-   **Authentication**

[Dash OpenSource provides users with basic authentication measures](https://dash.plotly.com/authentication) to include in their Dash applications. It must be installed separately to dash using the command `pip install dash-auth`, and then imported at the top of your Python script using `import dash-auth`.

-   **Maintenance**

Dash maintains a clear changelog, and so on returning to an application, one has to simply read the release notes that had been uploaded during ones absence to find any new features that had been added, or if any features had deprecation warnings.

[Is it mostly used in academia or industry (or both)?]{.ul}

Plotly Dash is popular in both fields. It's different because it's free, online, doesn't need to be downloaded, and supports collaboration. Plotly Dash also lets one make and share beautiful, interactive graphs.

-   **Students**

Plotly Dash is a platform for learning about and doing data visualization. They have tutorials, trainings, videos, a feed of graphs, and blog posts on both introductory and advanced topics. For example, what line types are available? When and how should you change the opacity of a scatter plot? The goal is to be easy for first-time, non-technical users yet powerful and scientific for advanced users.

-   **Professionals**

For technical users, they offer APIs and training for scientific graphing languages and libraries: MATLAB, Python, R, Node.js, Julia, and Excel. Their local deployments, private sharing, and educational packages allow labs and educational teams to use Dash on-premises. Plotly Dash is used on-premise by a quantum research lab at the University of Copenhagen, SpaceX, and Aerospace Corporation.

### Links

[Official webpage of Dash](https://plotly.com/dash/)\
\
[Public repository](https://github.com/plotly/dash)\
\
