---
title: Resources 
description: Dash
---
 
### Brief description

Dash is new in the Python ecosystem which was first introduced in 2017. It is a free Python library for creating reactive, web-based applications. This document is to give users an extensive list of resources to learn Dash. The list is composed of three main parts of resources, namely `Introduction to Dash`, `Tutorials`, and `Public curated resources`.


### Long description

Dash is an open source library for creating reactive, web-based applications, which was released under the permissive MIT license.
In 2017 Plotly launched the initial beta version of Dash, with the framework’s initial release coming in early 2019. In 2019 Dash for R was created, and in 2020 Dash for Julia was created, leading to a language-agnostic framework built upon the most common data science programming languages.
Developing web application in Dash is straight forward as its uses Python programming as its base and it is made on python flask framework.
Those who use Python for data analysis, data exploration, visualization, modelling, instrument control, and reporting will find immediate use for Dash. This document is to give users an extensive list of resources to learn Dash. 

To get to know Dash better as a newbie, the following tutorials and articles can generalize what it is all about from basic level to a high-level. Firstly, it is suggested that beginners should start with some resources about `Introduction to Dash`. Youtube is a great resources since it contains short videos with good contents without making the new learners feeling overwhelmed. Once getting used to the basic idea of Dash, it is a good time to move forward with more advanced `Tutorials` to dig deeper into each specific topics of Dash. Again, the `Dash Plottly Channel` on Youtube is a very good resource. During the process of working with Dash, if learners encounter any obstacles, Dash communities and other resources under `Public curated resources` are very useful.  

#### Introduction to Dash
Short introduction to Dash on various platform.

**Youtube Resources**
- [Dash - A New Framework for Building User Interfaces](https://www.youtube.com/watch?v=sea2K4AuPOk)
- [Introduction to Dash Plotly - Data Visualization in Python](https://www.youtube.com/watch?v=hSPmj7mK6ng)
- [Dash in 5 Minutes](https://www.youtube.com/watch?v=e4ti2fCpXMI)

**Publications**
- [Dash for Beginners : Python Dashboards](https://towardsdatascience.com/dash-for-beginners-create-interactive-python-dashboards-338bfcb6ffa4)
- [Introduction to Dash in Python - GeeksforGeeks](https://www.geeksforgeeks.org/introduction-to-dash-in-python/)
Note: You might need to register to access to these resources. 

**Webpages**
- [Getting started with data visualization with Dash](https://developer.twitter.com/en/docs/tutorials/getting-started-dash)
- [Develop Data Visualization Interfaces in Python With Dash](https://realpython.com/python-dash/)

### Tutorials
Online tutorials with comprehensive curriculum that guide learners/users through building dashboards on Dash:

**Youtube Resources**
This is a Youtube channel of Adam who is passionate about Dash Plotly. This channel has a variety of topics from basic to advance.
- [Dash Plotty Channel](https://www.youtube.com/c/CharmingData/featured)

This is Youtube series includes very short videos which will be convenient for busy learners. 
- [Plotly Dash Complete Tutorial](https://www.youtube.com/playlist?list=PLH6mU1kedUy8fCzkTTJlwsf2EnV_UvOV-)

This 1-hour video provides complete coverage of Plotly with many real world examples.
-[Plotly Tutorial 2021](https://www.youtube.com/watch?v=GGL6U0k8WYA)

**Publications**
- [Advanced Guide to Plotly Dash Interactive Visualizations](https://towardsdatascience.com/python-for-data-science-advanced-guide-to-plotly-dash-interactive-visualizations-8586b0895032)
- [Advancing to Professional Dashboard with Python, using Dash](https://towardsdatascience.com/advancing-to-professional-dashboard-with-python-using-dash-and-plotly-1e8e5aa4c668)
- [Challenges with Dash](https://medium.com/analytics-vidhya/5-challenges-when-using-plotly-dash-for-interactive-web-apps-849f442582f7)

Note: You might need to register to access to these resources. 

**Webpages/Blogposts**

Two technologies comparison for building web applications:
- [Dash vs. Shiny](https://appsilon.com/dash-vs-shiny/)

A blogpost to compare strengths and weaknesses of the two libraries. All in all, there's no best option. 
- [Dash vs. Bokeh](https://pauliacomi.com/2020/06/07/plotly-v-bokeh.html)

### Public curated resources

**Communities**

These communities include discussions, Q&A, help forums which are great resources for new learners. 
- [Dash Community](https://community.plotly.com/)
- [Dash Stackoverflow Community](https://stackoverflow.com/questions/tagged/plotly-dash)

**GitHub**

A repository compiles great resources.
- [Awesome Dash Github Repo ](https://github.com/ucg8j/awesome-dash)

- [Dash recipes](https://github.com/plotly/dash-recipes)

**Webinars/Webpages**

To find inspiration for your projects, these examples are very helpful as they are a collection of data dashboards with real life data, for various topics.
- [Dashboards by Dash](https://www.dashboardom.com/)
- [Dash Gallery](https://dash.gallery/Portal/)
- [Plotly Webbinars](https://plotly.com/resources/webinars/)

### References
- https://medium.datadriveninvestor.com/plotly-dash-everything-you-need-to-know-bc09a5e45395
- https://medium.com/plotly/introducing-dash-5ecf7191b503
