---
title: Resources - Shiny
description: none
---

### Brief description

Shiny may be one of the most popular apps for interactive Dashboards, and such popularity can be witnessed by vast numbers of resources over both online and offline resources. This report introduces useful resources for the Shiny app for both beginners and experts. 

The two most useful resources where I could obtain most of information were [Rstudio](https://shiny.rstudio.com/) and [Awesome R Shiny](https://grabear.github.io/awesome-rshiny/)


### Long description

The following list shows resources for Shiny apps

#### 1. Tutorial
* **[Shiny from RStudio](https://shiny.rstudio.com/tutorial/)** : 32 Video tutorials (grouped in 3 parts), 4 videos from RStudio conference and webinars

* **[Shiny tutorials and cheat sheet](http://zevross.com/blog/2016/04/19/r-powered-web-applications-with-shiny-a-tutorial-and-cheat-sheet-with-40-example-apps/)** : includes both codes and appearances of the corresponding apps, has great interactivity
* **[a gRadual intRoduction to Shiny](https://laderast.github.io/gradual_shiny/)** : Introductory workshop to basic Shiny Concept, recommended for intermediate R users

* **[Building Shiny apps](https://deanattali.com/blog/building-shiny-apps-tutorial/)** : An interactive tutorials

* **[Data Professor](https://www.youtube.com/c/DataProfessor)** : Youtube Channel with 112K subscribers

* **[Appsilon](https://www.youtube.com/channel/UC6LqpR5qBfNlQp5mVIVsthA)** : Youtube Channel with 1.7K subscribers

#### 2. Webinars
* **[RStudio Webinars](https://www.rstudio.com/resources/webinars/)** : 14 webinar videos related to Shiny, also includes videos for other useful contents such as python and R

#### 3. eBooks
* **[“Mastering Shiny”](https://mastering-shiny.org/)**

* **[“Engineering Production-Grade Shiny Apps”](https://engineering-shiny.org/)**

* **[“Outstanding User Interfaces with Shiny“](https://unleash-shiny.rinterface.com/index.html)**

#### 4. Shiny Gallery
* **[Shiny from RStudio](https://shiny.rstudio.com/gallery/)** : Gallery from RStudio

* **[ShinyApps: Experience Statistics](http://shinyapps.org/)** : includes many Shiny examples related to statistics

* **[Awesome-shiny-apps-for-statistics](https://github.com/huyingjie/Awesome-shiny-apps-for-statistics)**: includes many Shiny examples related to statistics, machine learning, many more (some examples includes K-Means, Bayesian Analysis, Hypothesis Testing, etc.)

#### 5. Conferences
* **[rstudio::conf](https://www.rstudio.com/conference/)** : conference from RStudio, covers not only the Shiny apps but many other useful stuffs (2 day workshops and 2 day conference)

* **[Appsilon Shiny Conferences](https://appsilon.com/appsilon-shiny-conference-2022-announcement/)** : relatively new conference (Appsilon was founded in 2013 by people from Google, Microsoft, Bank of America and Domino Data Lab)

#### 6. Communities
* **[RStudio Community](https://community.rstudio.com/)** : includes info about Shiny and many other useful topics on R

* **[R-bloggers](https://www.r-bloggers.com/)** : includes info about Shiny and many other useful topics on R, machine learning, etc.

* **[R Shiny in Reddit](https://www.reddit.com/r/rshiny/)** : created in 2013, over 2000 members

#### 7. Miscellaneous
* **[Shiny Function References](https://shiny.rstudio.com/reference/shiny/latest/)** : includes all the references of Shiny functions

* **[Tagged questions regarding Shiny in Stack Overflow](https://stackoverflow.com/questions/tagged/shiny)** : includes 24,961 questions regarding Shiny 

* **[Awesome R Shiny](https://grabear.github.io/awesome-rshiny/)** : github page that literally has everything about Shiny apps (includes links to various communities, deployments, tutorials, tools, books, etc.)

